name:                metronome
version:             0.1.0.0
synopsis:            Simple project template from stack
description:         Please see README.md
homepage:            https://github.com/5outh/metronome#readme
license:             BSD3
author:              Benjamin Kovach
maintainer:          benjamin@kovach.me
copyright:           MIT
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - turtle
  - text
  - containers
  - directory
  - optparse-generic

executables:
  metronome:
    ghc-options: -threaded -Wall -rtsopts -with-rtsopts=-N
    source-dirs:      src
    main:             Main.hs
